site_name: IWebCore
docs_dir: md
site_dir: docs

plugins:
  - search
  - awesome-pages

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - bash
    - json
    - go
    - c
    - cpp
    - java
    - javascript
    - php
    - ruby
    - swift
    - sql
    - xml
    - markdown
    - yaml
    - ini
    - dockerfile
    - python
    - powershell