site_name: IWebCore
docs_dir: md
site_dir: docs

plugins:
  - search
  - awesome-pages
  # - i18n:
  #   docs_structure: suffix
  #   languages:
  #     - locale: en
  #       name: English
  #       build: true
  #     - locale: zh
  #       default: true
  #       name: 中文
  #       build: true

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - bash
    - json
    - go
    - c
    - cpp
    - java
    - javascript
    - php
    - ruby
    - swift
    - sql
    - xml
    - markdown
    - yaml
    - ini
    - dockerfile
    - python
    - powershell

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
    linenums: true
- mdx_include:
    base_path: docs
- admonition
- codehilite:
    guess_lang: false
    linenums: true
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.extra
- pymdownx.tasklist